services:
  solara:
    container_name: solara_labeler
    build: .
    volumes:
      - /workspace/Denys/solar/ortho-labeling/data/:/home/jovyan/data
      - /workspace/Denys/solar/solara-labeler/:/home/jovyan/solara-labeler
    ports:
      - "8600:8765"
      - "8000:8888"
