services:
  solara:
    container_name: solara_labeler
    build: .
    volumes:
      - /workspace/Denys/solar/ortho-labeling/data/:/home/jovyan/data
    ports:
      - "8600:8765"
      - "8851:8888"
