services:
  solara:
    container_name: solara_labeler
    build: .
    volumes:
      - /workspace/Denys/solar/solara-labeler/:/home/jovyan/solara-labeler
      - /workspace/Denys/solar/data/:/home/jovyan/solara-labeler/src/public/
    ports:
      - "8600:8765"
      - "8000:8888"
